### ISSUE TITLE
queryString中传入是中文的时候，被编码

### ISSUE THREAD

**Issue by EslRain** [F-loat/mpvue-router-patch#12]
![image](https://user-images.githubusercontent.com/25892605/40366774-8fd07712-5e0a-11e8-9210-ff1f438eb467.png)

![image](https://user-images.githubusercontent.com/25892605/40366751-87db061c-5e0a-11e8-91b0-cdaa59988a70.png)

**Comment by F-loat** [comment]
暂时去除了编码转换，后面重构时看看能不能自动编码解码，目前解码这块没法很好地处理，尤其是分享出去地页面
