### ISSUE TITLE
如何获取页面导航堆栈？

### ISSUE THREAD

**Issue by Vultur** [F-loat/mpvue-router-patch#14]
如何获取类似原生 getCurrentPages() 的页面堆栈信息？

**Comment by F-loat** [comment]
目前不支持这个，有尝试在 vue-router 的基础上做修改，大部分功能都可以支持，但是没什么好的办法检测到小程序自身路由的变化，例如后退和 tabbar 切换，可能只能在 onShow 里做同步了，后面有时间再完善

**Comment by F-loat** [comment]
目前你还是调用 getCurrentPages 这个方法吧

**Comment by davidlin88** [comment]
@F-loat 我想返回上一页时修改目标页面的data，尝试了[getCurrentPages()](https://github.com/Meituan-Dianping/mpvue/issues/558)，将想触发的方法放在与methods同级，但打印出prevPage没有我挂的方法，有什么办法能实现呢

**Comment by F-loat** [comment]
@davidlin88 建议在上一页的 onShow 里处理，跳转前在全局存个数据

**Comment by davidlin88** [comment]
其实我挂methos同级的方法开始调用成功过 后来不知怎么打印都打印不出了ε=(´ο｀*)))唉 只能用vuex了吗
