### ISSUE TITLE
怎么使用啊？？

### ISSUE THREAD

**Issue by wjf9492** [F-loat/mpvue-router-patch#16]
在主页面 的main中已经配置了，为什么还会报错呢？
![1536289703361](https://user-images.githubusercontent.com/24648326/45196365-72726580-b28e-11e8-9321-f1fb53111537.jpg)
![1536289684694](https://user-images.githubusercontent.com/24648326/45196382-7e5e2780-b28e-11e8-8a57-86d91ad1f0b4.jpg)

**Comment by davidlin88** [comment]
`this.$router.back()`
