### ISSUE TITLE
build 环境

### ISSUE THREAD

**Issue by mazusheng** [F-loat/mpvue-router-patch#3]
在build的时候报错
ERROR in static/js/vendor.js from UglifyJs
Name expected [./~/mpvue-router-patch/index.js:6,0][static/js/vendor.js:15,8]

  Build failed with errors.
查阅相关后发现是uglify 不支持es6

能在本项目中用babel编译成es5版本吗？

**Comment by F-loat** [comment]
可以参考这个 pr 修改下，mpvue 相关的库目前不是很有必要做打包处理 https://github.com/mpvue/mpvue-quickstart/pull/18

**Comment by mazusheng** [comment]
好的，谢谢
